### ISSUE TITLE
Licence for using code 

### ISSUE THREAD

**Issue by jdkent** [effigies/curriculum_vitae#1]
Hi Chris, 

I really like the formatting of your C.V. and I was wondering if this code is open (i.e. could I use this template for my own C.V.)? I especially appreciate how you made your name bold in all your publications/talks/etc., I'm just starting to read up on Bibtex, but that function still looks like magic.

Best,
James

**Comment by effigies** [comment]
All of the code is open. I'll need to track down the licenses to know exactly how open. I'll add a license file when I figure that out, but feel free to use this in the meantime.

**Comment by jdkent** [comment]
Thank You!

**Comment by effigies** [comment]
Licensed CC BY-SA 4.0. Individual files may be licensed differently. In particular, `cvbib.bst` is under the LaTeX Project Public License, as noted in the comments at its start.
